apiVersion: v1
kind: ReplicationController
metadata:
  name: dap-rc
  namespace: dap
spec:                     
  replicas: 3
  selector:
    rc-name: rc-dap 
  template:               # pod definition starts from here
    metadata:
      name: pod-dap
      labels:
        rc-name: rc-dap
    spec:
      containers:
        - name: container-dap
          image: melikktly/spring-demo:2.0.0
          #image: melikktly/spring-demo:2.0.0
          #image: melikktly/demo:2.0.0
          #image: sadedil/simpleinfoserver:2.0.0
          ports:
            - containerPort: 80