apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: simple-application
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      mykey: myvalue
  template:
    metadata:
      name: pod4
      labels:
        mykey: myvalue
    spec:
      containers:
      - name: postgres
        image: postgres:10.1
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: analytics
          - name: POSTGRES_USER
            value: melik
          - name: POSTGRES_PASSWORD
            value: mendix