apiVersion: v1
kind: Service
metadata:
  name: postgreservice
  namespace: simple-application
spec:
  type: LoadBalancer
  selector:
    mykey: myvalue
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432
  externalIPs:
    - 20.82.66.117
