apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: simple-application
spec:                     
  replicas: 1
  selector:
    matchLabels:
      mykey: myapp
  template:               # pod definition starts from here
    metadata:
      name: app
      labels:
        mykey: myapp
    spec:
      containers:
        - name: app
          #image: melikktly/spring-demo:2.0.0
          image: melikktly/demo:1.0.0-v1
          ports:
          - containerPort: 8080
          env:
            - name: PG_CONNECTION_ENTPOINT
              #value: '20.82.66.117'
              valueFrom: 
                secretKeyRef: 
                  key: entpoint
                  name: mysecret1
            - name: PG_CONNECTION_CLIENT
              valueFrom: 
                secretKeyRef: 
                  key: client
                  name: mysecret1
              #value: postgresql
            - name: PG_CONNECTION_PORT
              valueFrom: 
                  secretKeyRef: 
                    key: port
                    name: mysecret1
              #value: '5432'
            - name: PG_CONNECTION_USER
              valueFrom: 
                secretKeyRef: 
                  key: user
                  name: mysecret1
              #value: melik
            - name: PG_CONNECTION_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: mysecret1
              #value: mendix
            - name: PG_CONNECTION_DB
              valueFrom: 
                  secretKeyRef: 
                    key: connectiondb
                    name: credentials
              #value: analytics