apiVersion: v1              #service definition starts from here
kind: Service
metadata:
  name: nodejs-service
  namespace: simple-application
spec:
  type: LoadBalancer            # Try LoadBalancer if you deploy this yaml to any cloud service
  selector:
    mykey: myapp
  ports:
  - name: http
    protocol: TCP
    port: 8080                                  # The application's port, running in the container
    targetPort: 8080                         # By default the targetPort will be set to the same value as the port fields